######################################################################
# Automatically generated by qmake (2.01a) mer. 6. août 11:25:23 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MNotePad.h
SOURCES += main.cpp MNotePad.cpp
